import 'package:flutter/material.dart';

class LightTheme {
  final ThemeData theme = ThemeData(
    appBarTheme: AppBarTheme(brightness: Brightness.light),
    visualDensity: VisualDensity.adaptivePlatformDensity,
    brightness: Brightness.light,
    primarySwatch: MaterialColor(0xffff6040, {
      50: Color.fromRGBO(255, 96, 64, .1),
      100: Color.fromRGBO(255, 96, 64, .2),
      200: Color.fromRGBO(255, 96, 64, .3),
      300: Color.fromRGBO(255, 96, 64, .4),
      400: Color.fromRGBO(255, 96, 64, .5),
      500: Color.fromRGBO(255, 96, 64, .6),
      600: Color.fromRGBO(255, 96, 64, .7),
      700: Color.fromRGBO(255, 96, 64, .8),
      800: Color.fromRGBO(255, 96, 64, .9),
      900: Color.fromRGBO(255, 96, 64, 1),
    }),
    primaryColor: Color(0xffff6040),
    primaryColorBrightness: Brightness.dark,
    primaryColorLight: Color(0xffff7053),
    primaryColorDark: Color(0xffe6563a),
    accentColor: Color(0xffff6040),
    accentColorBrightness: Brightness.light,
    canvasColor: Color(0xffffffff),
    scaffoldBackgroundColor: Color(0xffffffff),
    bottomAppBarColor: Color(0xffffffff),
    cardColor: Color(0xffffffff),
    dividerColor: Color(0x1f000000),
    highlightColor: Color(0x66bcbcbc),
    splashColor: Color(0x66c8c8c8),
    selectedRowColor: Color(0xfff5f5f5),
    unselectedWidgetColor: Color(0x8a000000),
    disabledColor: Color(0x61000000),
    buttonColor: Color(0xffff6040),
    toggleableActiveColor: Color(0xffff6040),
    secondaryHeaderColor: Color(0xffffffff),
    textSelectionColor: Color(0xffff6040),
    cursorColor: Color(0xffff6040),
    textSelectionHandleColor: Color(0xffff6040),
    backgroundColor: Color(0xffffffff),
    dialogBackgroundColor: Color(0xffffffff),
    indicatorColor: Color(0xffe3f2fd),
    buttonTheme: ButtonThemeData(
      textTheme: ButtonTextTheme.normal,
      minWidth: 88,
      height: 36,
      padding: EdgeInsets.only(top: 0, bottom: 0, left: 16, right: 16),
      shape: StadiumBorder(
        side: BorderSide(
            color: Color(0xff000000), width: 0, style: BorderStyle.none),
      ),
      alignedDropdown: true,
      buttonColor: Color(0xffff6040),
      disabledColor: Color(0x61000000),
      highlightColor: Color(0x29000000),
      splashColor: Color(0x1f000000),
      focusColor: Color(0x1f000000),
      hoverColor: Color(0x0a000000),
      colorScheme: ColorScheme(
        primary: Color(0xffff6040),
        primaryVariant: Color(0xffff6040),
        secondary: Color(0xffff6040),
        secondaryVariant: Color(0xffff6040),
        surface: Color(0xffffffff),
        background: Color(0xffff6040),
        error: Color(0xffffffff),
        onPrimary: Color(0xffffffff),
        onSecondary: Color(0xffffffff),
        onSurface: Color(0xff000000),
        onBackground: Color(0xffffffff),
        onError: Color(0xffffffff),
        brightness: Brightness.light,
      ),
    ),
    textTheme: TextTheme(
      headline1: TextStyle(
        color: Color(0x8a000000),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
        fontFamily: 'Poppins',
      ),
      headline2: TextStyle(
        color: Color(0x8a000000),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
        fontFamily: 'Poppins',
      ),
      headline3: TextStyle(
        color: Color(0x8a000000),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
        fontFamily: 'Poppins',
      ),
      headline4: TextStyle(
        color: Color(0x8a000000),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
        fontFamily: 'Poppins',
      ),
      headline5: TextStyle(
        color: Color(0xdd000000),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
        fontFamily: 'Poppins',
      ),
      headline6: TextStyle(
        color: Color(0xdd000000),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
        fontFamily: 'Poppins',
      ),
      subtitle1: TextStyle(
        color: Color(0xdd000000),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
        fontFamily: 'Poppins',
      ),
      bodyText1: TextStyle(
        color: Color(0xdd000000),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
        fontFamily: 'Poppins',
      ),
      bodyText2: TextStyle(
        color: Color(0xdd000000),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
        fontFamily: 'Poppins',
      ),
      caption: TextStyle(
        color: Color(0x8a000000),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
        fontFamily: 'Poppins',
      ),
      button: TextStyle(
        color: Color(0xdd000000),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
        fontFamily: 'Poppins',
      ),
      subtitle2: TextStyle(
        color: Color(0xff000000),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
      ),
      overline: TextStyle(
        color: Color(0xff000000),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
        fontFamily: 'Poppins',
      ),
    ),
    primaryTextTheme: TextTheme(
      headline1: TextStyle(
        color: Color(0xb3ffffff),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
        fontFamily: 'Poppins',
      ),
      headline2: TextStyle(
        color: Color(0xb3ffffff),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
        fontFamily: 'Poppins',
      ),
      headline3: TextStyle(
        color: Color(0xb3ffffff),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
        fontFamily: 'Poppins',
      ),
      headline4: TextStyle(
        color: Color(0xb3ffffff),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
        fontFamily: 'Poppins',
      ),
      headline5: TextStyle(
        color: Color(0xffffffff),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
        fontFamily: 'Poppins',
      ),
      headline6: TextStyle(
        color: Color(0xffffffff),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
        fontFamily: 'Poppins',
      ),
      subtitle1: TextStyle(
        color: Color(0xffffffff),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
        fontFamily: 'Poppins',
      ),
      bodyText1: TextStyle(
        color: Color(0xffffffff),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
        fontFamily: 'Poppins',
      ),
      bodyText2: TextStyle(
        color: Color(0xffffffff),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
        fontFamily: 'Poppins',
      ),
      caption: TextStyle(
        color: Color(0xb3ffffff),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
        fontFamily: 'Poppins',
      ),
      button: TextStyle(
        color: Color(0xffffffff),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
        fontFamily: 'Poppins',
      ),
      subtitle2: TextStyle(
        color: Color(0xffffffff),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
        fontFamily: 'Poppins',
      ),
      overline: TextStyle(
        color: Color(0xffffffff),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
        fontFamily: 'Poppins',
      ),
    ),
    accentTextTheme: TextTheme(
      headline1: TextStyle(
        color: Color(0xff000000),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
        fontFamily: 'Poppins',
      ),
      headline2: TextStyle(
        color: Color(0xff000000),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
        fontFamily: 'Poppins',
      ),
      headline3: TextStyle(
        color: Color(0xff000000),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
        fontFamily: 'Poppins',
      ),
      headline4: TextStyle(
        color: Color(0xff000000),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
        fontFamily: 'Poppins',
      ),
      headline5: TextStyle(
        color: Color(0xff000000),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
        fontFamily: 'Poppins',
      ),
      headline6: TextStyle(
        color: Color(0xff000000),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
        fontFamily: 'Poppins',
      ),
      subtitle1: TextStyle(
        color: Color(0xff000000),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
        fontFamily: 'Poppins',
      ),
      bodyText1: TextStyle(
        color: Color(0xff000000),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
        fontFamily: 'Poppins',
      ),
      bodyText2: TextStyle(
        color: Color(0xff000000),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
        fontFamily: 'Poppins',
      ),
      caption: TextStyle(
        color: Color(0xff000000),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
        fontFamily: 'Poppins',
      ),
      button: TextStyle(
        color: Color(0xff000000),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
        fontFamily: 'Poppins',
      ),
      subtitle2: TextStyle(
        color: Color(0xff000000),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
        fontFamily: 'Poppins',
      ),
      overline: TextStyle(
        color: Color(0xff000000),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
        fontFamily: 'Poppins',
      ),
    ),
    inputDecorationTheme: InputDecorationTheme(
      labelStyle: TextStyle(
        color: Color(0xff000000),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
      ),
      helperStyle: TextStyle(
        color: Color(0xff000000),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
      ),
      hintStyle: TextStyle(
        color: Color(0xff000000),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
      ),
      errorStyle: TextStyle(
        color: Color(0xff000000),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
      ),
      errorMaxLines: null,
      isDense: false,
      contentPadding: EdgeInsets.only(top: 12, bottom: 12, left: 15, right: 15),
      isCollapsed: false,
      prefixStyle: TextStyle(
        color: Color(0xff000000),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
      ),
      suffixStyle: TextStyle(
        color: Color(0xff000000),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
      ),
      counterStyle: TextStyle(
        color: Color(0xff000000),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
      ),
      filled: false,
      fillColor: Color(0x00000000),
      errorBorder: OutlineInputBorder(
        borderSide: BorderSide(color: Colors.yellow),
        borderRadius: BorderRadius.all(Radius.circular(30)),
      ),
      focusedBorder: OutlineInputBorder(
        borderSide: BorderSide(color: Color(0xffff6040)),
        borderRadius: BorderRadius.all(Radius.circular(30)),
      ),
      focusedErrorBorder: OutlineInputBorder(
        borderSide: BorderSide(color: Colors.yellow),
        borderRadius: BorderRadius.all(Radius.circular(30)),
      ),
      disabledBorder: OutlineInputBorder(
        borderSide: BorderSide(color: Colors.grey),
        borderRadius: BorderRadius.all(Radius.circular(30)),
      ),
      enabledBorder: OutlineInputBorder(
        borderSide: BorderSide(color: Color(0xffff6040)),
        borderRadius: BorderRadius.all(Radius.circular(30)),
      ),
      border: OutlineInputBorder(
        borderSide: BorderSide(color: Color(0xffff6040)),
        borderRadius: BorderRadius.all(Radius.circular(30)),
      ),
    ),
    iconTheme: IconThemeData(
      color: Color(0xff000000),
      opacity: 1,
      size: 24,
    ),
    primaryIconTheme: IconThemeData(
      color: Color(0xffffffff),
      opacity: 1,
      size: 24,
    ),
    sliderTheme: SliderThemeData(
      activeTrackColor: null,
      inactiveTrackColor: null,
      disabledActiveTrackColor: null,
      disabledInactiveTrackColor: null,
      activeTickMarkColor: null,
      inactiveTickMarkColor: null,
      disabledActiveTickMarkColor: null,
      disabledInactiveTickMarkColor: null,
      thumbColor: null,
      disabledThumbColor: null,
      thumbShape: null,
      overlayColor: null,
      valueIndicatorColor: null,
      valueIndicatorShape: null,
      showValueIndicator: null,
      valueIndicatorTextStyle: TextStyle(
        color: Color(0xffffffff),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
      ),
    ),
    tabBarTheme: TabBarTheme(
      indicatorSize: TabBarIndicatorSize.tab,
      labelColor: Color(0xffffffff),
      unselectedLabelColor: Color(0xb2ffffff),
    ),
    chipTheme: ChipThemeData(
      backgroundColor: Color(0xfff5f5f5),
      brightness: Brightness.light,
      deleteIconColor: Color(0xde000000),
      disabledColor: Color(0x0c000000),
      labelPadding: EdgeInsets.only(top: 0, bottom: 0, left: 8, right: 8),
      labelStyle: TextStyle(
        color: Color(0xde000000),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
      ),
      padding: EdgeInsets.only(top: 4, bottom: 4, left: 4, right: 4),
      secondaryLabelStyle: TextStyle(
        color: Color(0x3d000000),
        fontSize: null,
        fontWeight: FontWeight.w300,
        fontStyle: FontStyle.normal,
      ),
      secondarySelectedColor: Color(0xfff5f5f5),
      selectedColor: Color(0x3d000000),
      shape: StadiumBorder(
          side: BorderSide(
        color: Color(0xff000000),
        width: 0,
        style: BorderStyle.none,
      )),
    ),
    dialogTheme: DialogTheme(
      shape: RoundedRectangleBorder(
        side: BorderSide(
          color: Color(0xff000000),
          width: 0,
          style: BorderStyle.none,
        ),
        borderRadius: BorderRadius.all(
          Radius.circular(25.0),
        ),
      ),
    ),
    cardTheme: CardTheme(
      shape: RoundedRectangleBorder(
        side: BorderSide(
          color: Color(0xffff6040),
        ),
        borderRadius: BorderRadius.all(
          Radius.circular(30.0),
        ),
      ),
    ),
  );
}
